### ISSUE TITLE
Missing ~/Library/Jupyter plus ~/.sage belonging to root

### ISSUE THREAD

**Issue by GMS103** [3-manifolds/Sage_macOS#1]
I do not understand why a tmp directory should be used permanently.

**On macOS High Sierra 10.13.6:**
—Everything works.
—But:
```
$ which sage
/usr/local/bin/sage

$ ls -l /usr/local/bin/sage 
-rwxr-xr-x  1 root  wheel  95 Mar 17 21:11 /usr/local/bin/sage

$ cat /usr/local/bin/sage 
#!/usr/bin/env bash
/var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3/local/bin/sage "$@"

$ ls -l /var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3
lrwxr-xr-x  1 gms  wheel  87 Mar 31 15:39 /var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3 -> /Applications/SageMath/SageMath-9-2.app/Contents/Frameworks/Sage.framework/Versions/9.2

$ cat /usr/local/share/jupyter/kernels/sagemath/kernel.json 
{"argv": ["/var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3/local/bin/sage", "--python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"], "display_name": "SageMath 9.2", "language": "sage"}
```
**On macOS Big Sur 11.2.3:**
—Nothing works.
—For SageMath-9-2.app:  It opens and closes almost immediately without any message.  I do not know where to look, I have only found this in /private/var/log/system.log:
```
com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.computop.SageMath.1906839.1982340(502)> [11414]
com.apple.xpc.launchd[1] (application.org.computop.SageMath.1906839.1982340[75870]): Service exited with abnormal code: 1
```
—For command line sage:
```
% which sage
/usr/local/bin/sage

% ls -l /usr/local/bin/sage 
-rwxr-xr-x  1 root  wheel  95 Mar 17 21:11 /usr/local/bin/sage

% cat /usr/local/bin/sage 
#!/usr/bin/env bash
/var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3/local/bin/sage "$@"

% ls -l /var/tmp/sage*
ls: /var/tmp/sage*: No such file or directory

% cat /usr/local/share/jupyter/kernels/sagemath/kernel.json 
{"argv": ["/var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3/local/bin/sage", "--python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"], "display_name": "SageMath 9.2", "language": "sage"}
```

**Comment by NathanDunfield** [comment]
> I do not understand why a tmp directory should be used permanently.

This is done so that you can move or rename `/Applications/SageMath/SageMath-9-2.app/` without breaking Sage.   Currently, on all platforms, Sage hard codes a bunch of library paths on its first run so you can't move it after that.  See https://trac.sagemath.org/ticket/31076 for the technical details, but you should be able to drag `/Applications/SageMath/SageMath-9-2.app/`  to `/Applications/`  or `/Users/GMS103/Applications` and it should still work.

@culler will have to comment on the Big Sur issue.

**Comment by culler** [comment]
Thanks very much for helping to debug the beta version of the SageMath-9.2
app and for your understanding of the nature of beta software.

Needless to say, the app works fine for me on both of my Big Sur systems.
It is a very good point that the /usr/local/bin/sage script will not work
before the symlink in /var/tmp has been created.  That should happen as
soon as the app is launched.  But the script needs to explain to you, the
user, why it cannot run without the symlink.  I will address that.  But you
have another problem.

Can you please try running the main executable of the app from the command
line?  That should provide some information.  If you installed the app in
the usual place, namely /Applications/SageMath-9.2.app , then please try
running the script:
/Applications/SageMath-9-2.app/Contents/MacOS/SageMath
from your command line.  When I run that on my Big Sur system a small
window pops up, exactly as when the app is run by double-clicking.  You are
encountering some as yet unknown error at the very beginning, and you
should see a traceback in your terminal when you run the script directly.

- Marc

**Comment by GMS103** [comment]
Thanks to both of you for your answers.

**On macOS Big Sur 11.2.3:**
—For the app:

```
% /Applications/SageMath-9-2.app/Contents/MacOS/SageMath 
Traceback (most recent call last):
  File "/Applications/SageMath-9-2.app/Contents/MacOS/SageMath", line 253, in <module>
    SageApp().run()
  File "/Applications/SageMath-9-2.app/Contents/MacOS/SageMath", line 247, in run
    self.launcher = LaunchWindow()
  File "/Applications/SageMath-9-2.app/Contents/MacOS/SageMath", line 145, in __init__
    self.rescan()
  File "/Applications/SageMath-9-2.app/Contents/MacOS/SageMath", line 158, in rescan
    jupyter_openers = [f for f in os.listdir(jupyter_dir) if f[-4:] == 'html']
FileNotFoundError: [Errno 2] No such file or directory: '/Users/admin/Library/Jupyter/runtime'
```
which is normal as /Users/admin/Library/Jupyter does not exist.

—For command line sage:
```
% /Applications/SageMath-9-2.app/Contents/Frameworks/Sage.framework/Versions/Current/local/bin/sage
This SageMath application has been moved! Reconfiguring ...

Oh no!
You do not have permission to reconfigure this SageMath.
Please ask root to open the app.

The app will exit when you press a key.

% sudo /Applications/SageMath-9-2.app/Contents/Frameworks/Sage.framework/Versions/Current/local/bin/sage
Password:
This SageMath application has been moved! Reconfiguring ...
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.2, Release Date: 2020-10-24                     │
│ Using Python 3.8.5. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: 
```
and now:
```
% ls -l /var/tmp/sage*
lrwxr-xr-x  1 root  wheel  82 Mar 31 22:39 /var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3 -> /Applications/SageMath-9-2.app/Contents/Frameworks/Sage.framework/Versions/Current
```
However, the command line sage fails, because ~/.sage and everything inside belongs to root (very long and useless error message, I do not copy it here).
```
% sudo chown -R admin ~/.sage

% sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.2, Release Date: 2020-10-24                     │
│ Using Python 3.8.5. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: 
```

**Comment by GMS103** [comment]
For the sake of completeness, I should add that the problem of ~/Library/Jupyter not existing happens also in macOS High Sierra 10.13.6.  It did not manifest itself because I had installed another version of SageMath previously.  But trying to open
/Applications/SageMath-9-2.app/Contents/MacOS/SageMath
in a fresh account fails as indicated.

**Comment by culler** [comment]
Thank you.  That is very helpful.  We will need to check for the existence of ~/Library/Jupyter and to understand what is the natural way for that directory to be created in the first place.  There is not much we can do about
~/.sage being unwritable by its own user, but maybe we could at least provide a more helpful diagnostic.

- Marc

**Comment by culler** [comment]
Actually, we were already planning to change the app so that it uses a different, private, directory for the Jupyter profiles in ~/Application Support.  So that should take care of the ~/Library/Jupyter issue.

**Comment by culler** [comment]
I think that all of these issues (except having non-writable ~/.sage) have been addressed in the latest beta.2 release.  If you agree I will close this ticket and hopefully we can move to an actual release soon.  Thanks for the report.

**Comment by GMS103** [comment]
Yes, of course.
I shall test the new release and tell you how it goes.
Thank you very much for everything.

**Comment by culler** [comment]
I am closing this ticket as the issues have been addressed in the release.
