### ISSUE TITLE
Add warning when running sage -i

### ISSUE THREAD

**Issue by slel** [3-manifolds/Sage_macOS#10]
Since the app does not ship enough to build extra packages,
consider having `sage -i blah` warn that this is not supported,
instead of erroring out.

Some reports from users who tried to install extra packages:

- [sage-support discussion: sage -i gap_packages](https://groups.google.com/g/sage-support/c/NletjrinNhM/m/utEYheELBAAJ)
- [Ask Sage question 57450: sage -i pynormaliz](https://ask.sagemath.org/question/57450)

**Comment by culler** [comment]
This suggestion has been implemented in v1.2.1, so I am closing the ticket.
