### ISSUE TITLE
sage --pip install --editable /path/to/<foo> is not visible in Jupyter unless Jupyter can access that directory (e.g., via full disk permissions)

### ISSUE THREAD

**Issue by posita** [3-manifolds/Sage_macOS#15]
It was possible (if you worked around the lack of OpenSSL) on 9.1 to do something like `…/SageMath-9.1.app/…/sage --pip install --editable <foo>`, which would allow you to `import <foo>` in your Jupyter notebooks and receive updates as one hacked on the underlying library. This technique is **_very_** useful for development.

It appears that functionality is not longer working. After installing the recommended helper tools, `/usr/local/bin/sage --pip install --editable <foo>` appears to work (installing `foo` into `~/.sage/lib/python3.9/site-packages/<foo>.egg-link`). However, trying to access it in Jupyter will result in something like:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c28bce4280cc> in <module>
----> 1 import <foo>

ModuleNotFoundError: No module named '<foo>'
```

Replace `<foo>` with your favorite library not already included with Sage. If you can't think of anything, [`tinyec`](https://github.com/alexmgr/tinyec) has no dependencies and will stand in well to reproduce the above symptoms.

From a shell:

```
$ Python 3.9.2 (default, Jun 10 2021, 21:07:27)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinyec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tinyec'
>>> ^D
$ git clone https://github.com/alexmgr/tinyec.git
$ cd tinyec
$ sage --pip install --editable .
…
$ find ~/.sage/local -name '*tinyec*'
…/.sage/local/lib/python3.9/site-packages/tinyec.egg-link
$ sage --python
Python 3.9.2 (default, Jun 10 2021, 21:07:27)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinyec ; print(tinyec.__file__)
…/tinyec/tinyec/__init__.py
>>> ^D
```

From Jupyter:

```
import tinyec
```

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c28bce4280cc> in <module>
----> 1 import tinyec

ModuleNotFoundError: No module named 'tinyec'
```

Note that if you do **_not_** install the library via link to a local directory (i.e., do **_not_** use `--editable`), it will work:

From a shell:

```
$ sage --pip uninstall tinyec
Found existing installation: tinyec 0.3.1
Uninstalling tinyec-0.3.1:
  Would remove:
    …/.sage/local/lib/python3.9/site-packages/tinyec.egg-link
Proceed (y/n)? y
  Successfully uninstalled tinyec-0.3.1
$ sage --pip install tinyec
…
```

From Jupyter:

```
import tinyec
```

☝️ That works, perplexingly.

I bring this up because it appears to be a regression. (This technique **_worked_** for `SageMath-9.1.app`.)

**Comment by posita** [comment]
Okay, I think I figured out the root cause. From Jupyter:

```
import os
os.listdir("</path/to>/tinyec")
```

```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-4-07f88aceeb75> in <module>
      1 import os
----> 2 os.listdir("</path/to>/tinyec")

PermissionError: [Errno 1] Operation not permitted: '</path/to>/tinyec'
```

I realized that I was running `sage …` from my terminal app, which has been granted full disk access, so that might explain why that worked.

I looked into granting full disk access to the `python3.9` binary inside `SageMath-9-3.app`, but it is not selectable:

![wtf](https://user-images.githubusercontent.com/222581/123528481-ee8eff80-d6ac-11eb-9b76-1336867a959c.png)

**Comment by NathanDunfield** [comment]
First, thanks very much for the detailed report and initial diagnosis!

When you start Jupyter via `SageMath-9-3.app`, select as the notebook folder something that contains `tinyec` as a subfolder.   Jupyter and its kernels are only able to access files that are below that "notebook root" directory, so I think this will solve your problem.

If that doesn't work, you could start the Jupyter notebook server manually in a `Terminal.app` window by `sage -n`.  It should then inherit the full disk permissions.

However, I didn't test either of these, so let us know if either fix your problem.

**Comment by posita** [comment]
You beat me to the `sage -n` technique. That does indeed work (likely having inherited permissions from the terminal). I hadn't tried the root bit yet. Unfortunately, that technique doesn't work where the notebook and the linked development lib are in different locations. I started reading [this](https://developer.apple.com/forums/thread/107546) to see if I could figure out why I couldn't grant full disk perms to the internal `python3.9` binary. I **_suspect_** it's a code signing issue, but probably won't pursue too much further (at least not right away) since I have a work-around.

**Comment by NathanDunfield** [comment]
> I hadn't tried the root bit yet. Unfortunately, that technique doesn't work where the notebook and the linked development lib are in different locations. 

You can set the notebook root directory all the way up to `/` by selecting `Macintosh HD` in the file dialog selector in `SageMath.app`.  Then every file on your system will be below that and Jupyter should have full access do your disk.  Of course, you then have to navigate in the Jupyter file browser to the actual directory where your notebook lives, which is a bit annoying.

**Comment by NathanDunfield** [comment]
By the way, what version of macOS are you running?  I couldn't immediately duplicate what you're seeing in Catalina (10.15).

**Comment by posita** [comment]
Interesting. I'm running 10.15.7 (19H1217).

**Comment by culler** [comment]
I suspect that the reason the SageMath app cannot be directly given full disk access is that its main executable is actually a shell script which execs python3 to run itself as a python script.  As a wild guess, I think that giving /bin/sh full disk access might cause the app to inherit full disk access.

**Comment by posita** [comment]
> I suspect that the reason the SageMath app cannot be directly given full disk access is that its main executable is actually a shell script which execs python3 to run itself as a python script. As a wild guess, I think that giving /bin/sh full disk access might cause the app to inherit full disk access.

Yeah, that's why I looked into granting full disk access to the embedded `python3.9` binary in particular:

```
$ file -h SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3/local/bin/python3.9
SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3/local/bin/python3.9: Mach-O 64-bit executable x86_64
```

(See my [earlier comment](#issuecomment-869073868) with a screenshot.)

**Comment by culler** [comment]
I saw that.  But did you try granting permission to /bin/sh?

I think that might actually work whereas granting access to python would
not work because the system is not smart enough to recognize that the main
executable eventually gets run by python after it forks.  It can only
detect that the main executable initially is run by bin/sh (before the
fork).

**Comment by culler** [comment]
Incidentally, the disable-library-validation entitlement is used in order to allow loading unsigned python extension modules.  Without that entitlement, [Apple says](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation) that the "[Hardened Runtime] feature prevents a program from loading frameworks, plug-ins, or libraries unless they’re either signed by Apple or signed with the same Team ID as the main executable".

**Comment by posita** [comment]
Interesting. Can one change that parameter without resigning?

**Comment by culler** [comment]
As far as I know, nothing can be changed without resigning.

**Comment by culler** [comment]
If you want to experiment with code signing (experimentation being essentially the only way to find out anything about how it works) you can create a [self-signed certificate](https://support.apple.com/guide/keychain-access/create-self-signed-certificates-kyca8916/mac).

**Comment by culler** [comment]
I retested this using your tinyec example, and it now works fine to import tinyec.  The difference is that the main executable is no longer a shell script.  That has been the case for a few releases now.  I am sorry that I forgot to recheck this issue when I made that change.

I think I can close this now, though.
