### ISSUE TITLE
Beta release of SageMath-9.3.rc.4 running on pre 2013 Apple computers)?

### ISSUE THREAD

**Issue by Matthias-A-Steiner** [3-manifolds/Sage_macOS#18]
It's a pity that Sage_macOS v.1.1 isn't running on computers built before 2013. Does this also apply to the latest pre-release as of 12 Apr ? If that version is stable enough I would like to know if it runs on older machines and if it's worth replacing the latest stable Sage_macOS-9.2.

Tilda

**Comment by culler** [comment]
Instead, please try the just-released beta version of SageMath-9.4 (based on  Sage 9.4.beta4) and let us know if that works with older CPUs.  It was compiled with the -mno-avx2 flag.  Hopefully that will be enough to make it run on macs with pre-Haswell CPUs.  If you see a SIGILL crash, please provide a crash log with as much detail as possible.

**Comment by culler** [comment]
Closing this issue and merging with #16.
