### ISSUE TITLE
SIGILL crash on mid 2014 MacBook Pro

### ISSUE THREAD

**Issue by oppewala** [3-manifolds/Sage_macOS#21]
I've installed sage using the latest non-beta dmg file on my mid-2014 macbook pro. I can open the application and the window to open with Terminal or Jupyter pops up.

When I try to open with Terminal I get  this:
```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.3, Release Date: 2021-05-09                     │
│ Using Python 3.9.2. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
------------------------------------------------------------------------
(no backtrace available)
------------------------------------------------------------------------
Unhandled SIGILL: An illegal instruction occurred.
This probably occurred because a compiled module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

When I try to open with Jupyter, it is unable to run anything, and just says 'Kernel starting'.

**Comment by culler** [comment]
Your computer is too old to run the latest non-beta release.  Your CPU does not support the AVX2 instruction set which was assumed to be available when that release was compiled.  You should try installing the beta release.  It was compiled with the -mno-avx2 flag which should ensure that no AVX2 instructions appear in the executable code.  Please let us know if that works for you.

**Comment by culler** [comment]
Closing this issue and merging it with #16.
