### ISSUE TITLE
Not Running on MacBookPro (15-inch, Mid 2015)

### ISSUE THREAD

**Issue by brunoh2015** [3-manifolds/Sage_macOS#22]
Herebelow is what I get when I try to launch 9.4.rc0 on my MacBookPro with 2,8 GHz Quad-Core Intel Core i7, and MacOSX 11.5.1

Unhandled SIGILL: An illegal instruction occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
zsh: illegal hardware instruction  
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

PS. my previous issue with the beta of 9.4 or even 9.3 was not solved, so I cannot use Sage on this computer!

**Comment by culler** [comment]
Noted on the original ticket.  Closing this duplicate.
