### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by wbelau** [3-manifolds/Sage_macOS#24]
Running macOS Catalina version 10.15.7
After installing SageMath-9.3.app with add-on here a crash report.

Process:               python3.9 [8208]
Path:                  /Applications/SageMath-9-3.app/Contents/MacOS/SageMath
Identifier:            org.computop.SageMath
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           python3.9 [8208]
User ID:               501

Date/Time:             2021-08-10 14:51:05.154 +0200
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Anonymous UUID:        C4DE3C86-CBF0-6F24-A9D1-78A95A7E94CF

Sleep/Wake UUID:       5E4182A9-B51F-4828-B58F-01A3FD37C52A

Time Awake Since Boot: 12000 seconds
Time Since Wake:       2400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [8208]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libpython3.9.dylib            	0x000000010187032c 0x1017ad000 + 799532
1   libpython3.9.dylib            	0x000000010187016e _Py_DecodeUTF8Ex + 254
2   libpython3.9.dylib            	0x0000000101938fb1 Py_DecodeLocale + 49
3   libpython3.9.dylib            	0x00000001019191f0 _PyArgv_AsWstrList + 96
4   libpython3.9.dylib            	0x0000000101919d5c 0x1017ad000 + 1494364
5   libpython3.9.dylib            	0x000000010191b0c7 _Py_PreInitializeFromPyArgv + 295
6   libpython3.9.dylib            	0x000000010193d8ec 0x1017ad000 + 1640684
7   libpython3.9.dylib            	0x000000010193da3b Py_BytesMain + 43
8   libdyld.dylib                 	0x00007fff6cd40cc9 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000000000002f  rcx: 0x00007ffeee4645c8  rdx: 0x00007fbe12c07490
  rdi: 0x00007ffeee4645c0  rsi: 0x00007ffeee464cd6  rbp: 0x00007ffeee464590  rsp: 0x00007ffeee464568
   r8: 0x00007fbe12c07490   r9: 0x00007ffeee464c68  r10: 0x00007ffeee464cd0  r11: 0x8080808080808080
  r12: 0x0000000000000000  r13: 0x000000000000002f  r14: 0x6163696c7070412f  r15: 0x00007fbe12c07490
  rip: 0x000000010187032c  rfl: 0x0000000000010246  cr2: 0x00000001019c75a0
  
Logical CPU:     3
Error Code:      0x00000000
Trap Number:     6

Binary Images:
       0x10179b000 -        0x10179eff3 +SageMath (0) <353C3350-2970-3C72-A885-219F979F24F4> /Applications/SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3/local/bin/python3.9
       0x1017ad000 -        0x101a24fef +libpython3.9.dylib (0) <86451832-18F4-37B4-B6F5-FDA94047BF08> /Applications/SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3/local/lib/libpython3.9.dylib
       0x10bb9e000 -        0x10bc30267  dyld (750.7) <FCEF919F-F7F8-3C1A-B208-7ECDCB5EA674> /usr/lib/dyld
    0x7fff32b47000 -     0x7fff32fc7ff2  com.apple.CoreFoundation (6.9 - 1677.207) <80681FA0-C758-301F-8FB6-F23FFADD5481> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff697c1000 -     0x7fff697c3ff7  libDiagnosticMessagesClient.dylib (112) <C94F3B7B-1854-38EB-9778-834501C53B3F> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff69c97000 -     0x7fff69c98fff  libSystem.B.dylib (1281.100.1) <A8845AB6-40B5-357A-AF66-AEC21E112D65> /usr/lib/libSystem.B.dylib
    0x7fff6a013000 -     0x7fff6a065fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff6a066000 -     0x7fff6a07bffb  libc++abi.dylib (902) <E692F14F-C65E-303B-9921-BB7E97D77855> /usr/lib/libc++abi.dylib
    0x7fff6aae6000 -     0x7fff6aae8fff  libfakelink.dylib (149.1) <36146CB2-E6A5-37BB-9EE8-1B4034D8F3AD> /usr/lib/libfakelink.dylib
    0x7fff6abf8000 -     0x7fff6ae4ffff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff6bb8e000 -     0x7fff6bbc0fde  libobjc.A.dylib (787.1) <265783CE-6D74-36C9-B6D2-95D3910199EC> /usr/lib/libobjc.A.dylib
    0x7fff6c261000 -     0x7fff6c273ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff6cb22000 -     0x7fff6cb27ff3  libcache.dylib (83) <AF488D13-9E89-35E0-B078-BE37CC5B8586> /usr/lib/system/libcache.dylib
    0x7fff6cb28000 -     0x7fff6cb33fff  libcommonCrypto.dylib (60165.120.1) <C7912BE5-993E-3581-B2A0-6AABDC8C5562> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6cb34000 -     0x7fff6cb3bfff  libcompiler_rt.dylib (101.2) <49B8F644-5705-3F16-BBE0-6FFF9B17C36E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6cb3c000 -     0x7fff6cb45ff7  libcopyfile.dylib (166.40.1) <3C481225-21E7-370A-A30E-0CCFDD64A92C> /usr/lib/system/libcopyfile.dylib
    0x7fff6cb46000 -     0x7fff6cbd8fdb  libcorecrypto.dylib (866.140.2) <E9AAA2A6-D0D4-328A-BEA2-4DC5E513BA30> /usr/lib/system/libcorecrypto.dylib
    0x7fff6cce5000 -     0x7fff6cd25ff0  libdispatch.dylib (1173.100.2) <CD9C059C-91D9-30E8-8926-5B9CD0D5D4F5> /usr/lib/system/libdispatch.dylib
    0x7fff6cd26000 -     0x7fff6cd5cfff  libdyld.dylib (750.7) <AB99C9EE-7127-3451-89AB-339F8F2CEE61> /usr/lib/system/libdyld.dylib
    0x7fff6cd5d000 -     0x7fff6cd5dffb  libkeymgr.dylib (30) <DB3337BE-01CA-3425-BD0C-87774FC0CDC0> /usr/lib/system/libkeymgr.dylib
    0x7fff6cd6b000 -     0x7fff6cd6bff7  liblaunch.dylib (1738.140.3) <E2CFD17D-F36C-3734-8F37-16798799EF9E> /usr/lib/system/liblaunch.dylib
    0x7fff6cd6c000 -     0x7fff6cd71ff7  libmacho.dylib (959.0.1) <AA613A9C-961A-3B67-B696-4622FA59FC4E> /usr/lib/system/libmacho.dylib
    0x7fff6cd72000 -     0x7fff6cd74ff3  libquarantine.dylib (110.40.3) <F234E51D-FD0B-3EE4-B679-AE3EE9C536C3> /usr/lib/system/libquarantine.dylib
    0x7fff6cd75000 -     0x7fff6cd76ff7  libremovefile.dylib (48) <7C7EFC79-BD24-33EF-B073-06AED234593E> /usr/lib/system/libremovefile.dylib
    0x7fff6cd77000 -     0x7fff6cd8eff3  libsystem_asl.dylib (377.60.2) <1563EE02-0657-3B78-99BE-A947C24122EF> /usr/lib/system/libsystem_asl.dylib
    0x7fff6cd8f000 -     0x7fff6cd8fff7  libsystem_blocks.dylib (74) <0D53847E-AF5F-3ACF-B51F-A15DEA4DEC58> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6cd90000 -     0x7fff6ce17fff  libsystem_c.dylib (1353.100.4) <BCD3F031-4A3F-32CF-AB9A-D6EE7A7499D4> /usr/lib/system/libsystem_c.dylib
    0x7fff6ce18000 -     0x7fff6ce1bffb  libsystem_configuration.dylib (1061.141.2) <393137B7-3631-3450-B6F4-95EECD3ADDFF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6ce1c000 -     0x7fff6ce1ffff  libsystem_coreservices.dylib (114.1) <72857ADA-AA97-398B-B089-F50B2E89064B> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6ce20000 -     0x7fff6ce28fff  libsystem_darwin.dylib (1353.100.4) <19242BF1-BAF6-3DF0-AAD3-93E3E0870DBE> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6ce29000 -     0x7fff6ce30fff  libsystem_dnssd.dylib (1096.100.3) <EBB4C2C2-E031-3094-B40A-E67BF261D295> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6ce31000 -     0x7fff6ce32ffb  libsystem_featureflags.dylib (17) <29FD922A-EC2C-3F25-BCCC-B58D716E60EC> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff6ce33000 -     0x7fff6ce80ff7  libsystem_info.dylib (538) <8A321605-5480-330B-AF9E-64E65DE61747> /usr/lib/system/libsystem_info.dylib
    0x7fff6ce81000 -     0x7fff6ceadff7  libsystem_kernel.dylib (6153.141.35) <FDF91BB8-B353-3B7F-8644-3BA7AFBC2309> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6ceae000 -     0x7fff6cef9fef  libsystem_m.dylib (3178) <D1CF3A92-2424-3420-B375-DEED7AA68C53> /usr/lib/system/libsystem_m.dylib
    0x7fff6cefa000 -     0x7fff6cf21fff  libsystem_malloc.dylib (283.100.6) <8549294E-4C53-36EB-99F3-584A7393D8D5> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6cf22000 -     0x7fff6cf2fffb  libsystem_networkextension.dylib (1095.140.2) <F06C65C5-2CBE-313C-96E1-A09240F9FE57> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6cf30000 -     0x7fff6cf39ff7  libsystem_notify.dylib (241.100.2) <FA22F928-D91B-3AA5-96BB-3186AC0FB264> /usr/lib/system/libsystem_notify.dylib
    0x7fff6cf3a000 -     0x7fff6cf42fef  libsystem_platform.dylib (220.100.1) <009A7C1F-313A-318E-B9F2-30F4C06FEA5C> /usr/lib/system/libsystem_platform.dylib
    0x7fff6cf43000 -     0x7fff6cf4dfff  libsystem_pthread.dylib (416.100.3) <62CB1A98-0B8F-31E7-A02B-A1139927F61D> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6cf4e000 -     0x7fff6cf52ff3  libsystem_sandbox.dylib (1217.141.3) <F23A9D76-DD1C-38E7-8615-9B8B5B5AEE9A> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6cf53000 -     0x7fff6cf55fff  libsystem_secinit.dylib (62.100.2) <F80872AA-E1FD-3D7E-8729-467656EC6561> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6cf56000 -     0x7fff6cf5dffb  libsystem_symptoms.dylib (1238.120.2) <702D0910-5C34-3D43-9631-8BD215DE4FE1> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6cf5e000 -     0x7fff6cf74ff2  libsystem_trace.dylib (1147.120.1) <BC141783-66D9-3137-A783-211B38E49ADB> /usr/lib/system/libsystem_trace.dylib
    0x7fff6cf76000 -     0x7fff6cf7bff7  libunwind.dylib (35.4) <42B7B509-BAFE-365B-893A-72414C92F5BF> /usr/lib/system/libunwind.dylib
    0x7fff6cf7c000 -     0x7fff6cfb1ffe  libxpc.dylib (1738.140.3) <8DA7D88F-AE2F-3BCF-8426-8D041E57A9AA> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 8482
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=403.1M resident=0K(0%) swapped_out_or_unallocated=403.1M(100%)
Writable regions: Total=25.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=25.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            9260K        7 
MALLOC guard page                   16K        4 
STACK GUARD                          4K        1 
Stack                             16.0M        1 
__DATA                            2425K       48 
__DATA_CONST                        20K        1 
__LINKEDIT                       389.0M        6 
__OBJC_RO                         32.3M        1 
__OBJC_RW                         1908K        2 
__TEXT                            14.1M       46 
__UNICODE                          564K        1 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            465.2M      121 

Model: Macmini6,1, BootROM 422.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2,5 GHz, 8 GB, SMC 2.7f0
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142353137334442302D594B302020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142353137334442302D594B302020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1601.1)
Bluetooth: Version 7.0.6f8, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
USB Device: USB 3.0 Bus
USB Device: Hub in Apple Pro Keyboard
USB Device: USB Optical Mouse
USB Device: Apple Pro Keyboard
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 2.0 Hub
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: Mac mini, Apple Inc., 23.4

**Comment by culler** [comment]
Thank you.  The Core i5 (I5-3210M) CPU in your 2012 mac mini does not support some of the
instructions which are needed to run the 9.3 release.  This issue has been reported by several other owners of older macs and has been addressed in the SageMath-9.4 Release Candidate [prerelease](https://github.com/3-manifolds/Sage_macOS/releases/tag/v1.2-rc.0). Please install that prerelease instead, and please let us know whether it fixes your crash to do so.

**Comment by wbelau** [comment]
Thanks! The prerelease seems to work.

**Comment by culler** [comment]
Great! Thanks for letting us know.
