### ISSUE TITLE
installed sagetex.sty needs activation

### ISSUE THREAD

**Issue by herbs** [3-manifolds/Sage_macOS#27]
I didn't read the description for version 1.2.1 closely enough (Sorry!) and just now noticed that the .pkg now installs the present version of sagetex.sty in /usr/local/texlive/texmf-local/tex/latex/local. That's very useful, so thank you. There are two points to notice though:

1)The TeX Live distribution installed by MacTeX contains thousands of relatively small text file. To allow the distribution to quickly find files in the various directory trees a files is created for each tree listing the full directory structure of that tree. After installation of sagetex.sty the texmf-local (a good location) the TeX distribution has to activate it by including it in its available list; this is done by running `mktexlsr` (basically wirh `sudo` permissions since those directories are owned by root which is already being done by the insatller app).

2)While /usr/local/texlive/texmf-local/tex/latex/local is great for TeX Live installed by MacTeX (and related installers) that distribution can be custom installed and there are other TeX distributions available, like MikTeX, MacPorts and Fink, that use different install locations. I believe MacTeX installed TeX Live is the most popular but that should be noted.

**Comment by NathanDunfield** [comment]
With regards to (1), the `.pkg` installer does run `sudo mktexlsr` on the directory you mention.  Did MacTeX not automatically find `sagetex.sty` for you?

**Comment by herbs** [comment]
> On Oct 10, 2021, at 11:19 AM, Nathan Dunfield ***@***.***> wrote:
> 
> 
> With regards to (1), the .pkg installer does run sudo mktexlsr on the directory you mention. Did MacTeX not automatically find sagetex.sty for you?

Howdy,

It didn't seem to find it if I ran

kpsewhich sagetex.sty

which lists the active (i.e., first one found) version (i.e., the one I manually installed) or even

kpsewhich -a sagetex.sty

which lists all the versions found in the trees.

After running

sudo mktexlsr

manually both versions of the command listed and the one in .../local installed was the active one (after all .../local comes before .../sagetex in the LS-R file). I then removed the version I manually installed.

Right now I'm telling folks that have installed MacTeX to just run the `sudo mktexlsr` command and supply a copy of the present sagetex package for others. This is all for use with TeXShop.

PS: thanks for the work all you folks put in on maintaining the SageMath app for macOS.

Good Luck,

Herb Schulz
***@***.***

**Comment by herbs** [comment]
> On Oct 10, 2021, at 11:19 AM, Nathan Dunfield ***@***.***> wrote:
> 
> 
> With regards to (1), the .pkg installer does run sudo mktexlsr on the directory you mention. Did MacTeX not automatically find sagetex.sty for you?
> 

Howdy,

OK! I found my problem. When I installed the .pkg I only installed the sagetex.sty section and you must install everything to get the proper post-processing that includes the `mktexlsr`.

All is well, sorry for the noise.

Good Luck,

Herb Schulz
***@***.***

**Comment by culler** [comment]
Thanks Herb.  I am finally getting around to closing this, since all is well.
