### ISSUE TITLE
Failure to start Jupyter?

### ISSUE THREAD

**Issue by Tony-64** [3-manifolds/Sage_macOS#28]
Hi,

Unfortunately, I experienced a full system crash while I was running Sage 9.4 (screen going black, followed by a restart).  Following the crash, the app fails to start Jupyter (i.e. Safari complains that it failed to open the page localhost:8888/tree?token=... because it could not connect to the server localhost).  Upgrading to v1.2.1 didn't resolve the issue.

Interestingly enough, I can still start the Jupyter server by opening a terminal and running sage -n Jupyter.  Moreover, for any other account on the machine (such as the guest account), I can start Jupyter from the app as usual.  

I guess the crash messed up one or more of the access controls in my account.  However, I have no clue about how to resolve the issue.   Any thoughts about what can be wrong and how to repair it?  Would the app be able to give some diagnostic information to help the user troubleshoot the problem?

Thanks!

**Comment by NathanDunfield** [comment]
Try deleting the folder `~/Library/Application Support/SageMath/9.4/Jupyter`.

**Comment by Tony-64** [comment]
Yes, this worked!  It could be helpful to remove this folder automatically when the app detects a problem with starting Jupyter, or at the very least when running a fresh install.

**Comment by an-algebraic-geometer** [comment]
Hi! 

I have installed sagemath 9.4 on my mac but the app fails to start Jupyter saying the localhost is refused to connect. what should I do to fix this? 

Thanks!

**Comment by culler** [comment]
Please try the suggestion above: delete the folder ~/Library/Application Support/SageMath/9.4/Jupyter.

**Comment by an-algebraic-geometer** [comment]
Thanks a lot! finally, It worked.!!

**Comment by culler** [comment]
In the SageMath 9.5 release this will be handled automatically.  At startup the app will verify that each of the kernel process descriptors actually corresponds to a running kernel, and delete it if that is not the case.

I will close this ticket now and hope that we will not see this issue again with 9.5 or later.

**Comment by dimpase** [comment]
This seems to be still a problem for some users of Sage 10.3, see https://groups.google.com/g/sage-support/c/tMipcvECiFY/m/9jnN6FhmBAAJ
