### ISSUE TITLE
Beta release crashes on Apple Silicon

### ISSUE THREAD

**Issue by hdevalence** [3-manifolds/Sage_macOS#3]
Hi, I tried installing the "Beta release of SageMath-9.3 based on Sage 9.3.rc4" on an M1 Macbook Air. After installing, running `sage` errors with `SIGILL`:

```
hdevalence@deimos ~ % sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.3.rc4, Release Date: 2021-04-18                 │
│ Using Python 3.9.2. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
------------------------------------------------------------------------
(no backtrace available)
------------------------------------------------------------------------
Unhandled SIGILL: An illegal instruction occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
/usr/local/bin/sage: line 20: 19833 Illegal instruction: 4  $SYMLINK/local/bin/sage $@
hdevalence@deimos ~ % 
```

**Comment by culler** [comment]
Hi Henry,

Thanks for letting us know that the information on the release page is incomplete. The beta release is only built for Intel hardware( so SIGILL is a very apt error message).  I will add a notice on the release that it is only for Intel (so far). It is pretty amazing that the app was able to get far enough to deliver that message, even though the program is compiled for completely different hardware, don't you think?

Currently the SageMath app unpacks to 2.5 GB, of which something like 1.3GB are binary files.  I think that most people would not appreciate having an additional 1.3 GB of binary files which can not run on their computer, given that 2.5GB is already a lot.  Consequently I think that when we release the production version we will probably have two separate disk images.  But the final decision on that has not been made yet.  Sorry for the inconvenience!

**Comment by hdevalence** [comment]
No worries! I was able to get the previous 9.2 release running fine.

**Comment by culler** [comment]
I added an (Intel only) disclaimer in the title of the beta prerelease.

**Comment by NathanDunfield** [comment]
Interesting that 9.2 worked for Henry but 9.3 beta did not, I would have expected neither would function on Apple Silicon.  The difference could be that Rosetta 2 doesn't support some of Intel's vectorized instructions (AVX, AXV2, AXV512).  These could be invoked earlier in 9.3 or be included because Marc built the underlying binary for 9.3 on a fairly new Mac mini.  I bring this up because the later might cause problems for people with older Intel hardware.

**Comment by culler** [comment]
Yes, I was wondering how that was possible and had forgotten about Rosetta 2.  Indeed the 9.3rc4 version was compiled on my mac mini while the 9.2 version was based on an official binary distribution, which was presumably compiled on a virtual machine that emulates some relatively old Intel hardware.  This seems to argue for basing the final release of the 9.3 app on the official binary distribution.  That way the incompatibilities will be the same for the app as for the binary distribution and the responsibility for setting up the build environment will reside with the Sage project and not with this one, which only aims to package Sage.

I assume that Sage is planning to support both Intel and M1 for 9.3.  I wonder whether the plan is to provide separate tarballs for the two architectures or to build fat binaries.

The packaging process for the app should not care where the sage directory came from, unless I made some mistakes that I don't know about yet.

**Comment by NathanDunfield** [comment]
Porting to Apple Silicon won't happen for 9.3, see https://trac.sagemath.org/ticket/30592

**Comment by culler** [comment]
I am trying rebuilding Sage after configuring with -mno-avx in the CFLAGS.  What are the chances that will produce a Sage which does not use AVX?  Zero?

**Comment by NathanDunfield** [comment]
Probably higher than zero, but not very high given that processors with AVX started shipping in 2011.   You could also try `export SAGE_FAT_BINARY="yes"` which is supposed to disable some newer processor instructions (not sure which ones).

The more sophisticated libraries in Sage test for processor capability at runtime rather than compile time, but that's hardly all of them.
