### ISSUE TITLE
macOS Monterey 12.1 issue

### ISSUE THREAD

**Issue by Mr-iX** [3-manifolds/Sage_macOS#32]
I updated to macOS 12.1 this week and now when I try to launch a Jupyter Notebook I get an ERR_CONNECTION_REFUSED for http://localhost:8888/tree?token=[TOKEN]

**Comment by culler** [comment]
I am guessing this is the same problem as #28.  Please try following the recommendation in that ticket: delete the folder ~/Library/Application Support/SageMath/9.4/Jupyter

**Comment by Mr-iX** [comment]
Thanks that worked
