### ISSUE TITLE
Persisting preferences

### ISSUE THREAD

**Issue by GMS103** [3-manifolds/Sage_macOS#40]
Would it be possible to keep the previous settings when upgrading?
I.e., the choice of the user interface and the location of the notebooks.

**Comment by culler** [comment]
It would be possible.  It is not clear to me why it would be a good idea, though.

The preferences for SageMath-X.Y are stored in "~/Library/Application Support/SageMath/X.Y".  It would be possible to combine those directories and use the same preferences for all SageMath-X.Y apps.  One reason for keeping them separate is that they are distinct apps, and it seems very reasonable for people to want to have different preferences for different versions.  For example, when upgrading to a different version of Sage it might become necessary to adjust some worksheets.  So you might want to have different notebook directories for different versions of the app as you rewrite worksheets for the new version of Sage.

Also, it seems like resetting the preferences after an uprade is a 5 second job that is needed once every 5 or 6 months, so it is not a major inconvenience in the case where you do want to retain the preferences from the previous version.

**Comment by GMS103** [comment]
All right, no problem.
The raison was to avoid recalling where they are.
I shall copy `config` from one version to the next.
