### ISSUE TITLE
Sage_macOS 9.6 final release

### ISSUE THREAD

**Issue by Matthias-A-Steiner** [3-manifolds/Sage_macOS#41]
Dear Mark, 

thanks for your ongoing efforts to bring a Sage that installs out of the box to Mac users. I just wanted to know if there will be a SageMath-9.6_x86_64.dmg v.1.4.x build from the final/stabel release of Sage 9.6 as of 15 May 2022? 

Yours sincerely
Tilda

**Comment by herbs** [comment]
> On May 29, 2022, at 11:49 AM, Matthias-A-Steiner ***@***.***> wrote:
> 
> 
> Dear Mark,
> 
> thanks for your ongoing efforts to bring a Sage that installs out of the box to Mac users. I just wanted to know if there will be a SageMath-9.6_x86_64.dmg v.1.4.x build from the final/stabel release of Sage 9.6 as of 15 May 2022?
> 
> Yours sincerely
> Tilda
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

Howdy,

Go to <https://github.com/3-manifolds/Sage_macOS/releases>. When I run

sage -v

in Terminal with that version I get

SageMath version 9.6, Release Date: 2022-05-15

so that's the final release.

Good Luck,

Herb Schulz
***@***.***

**Comment by culler** [comment]
Yes, as Herb says, the current disk image is built from the 2022-5-15 release.
