### ISSUE TITLE
Released version 9.7 has wrong version of sagetex.sty embedded.

### ISSUE THREAD

**Issue by herbs** [3-manifolds/Sage_macOS#45]
The .pkg that installs sagetex.sty contains version 3.5 of that package instead of the version from 2021, 3.6.

**Comment by herbs** [comment]
The .pkg should be installing the version of sagetex.sty found in /Applications/SageMath-9-7.app/Contents/Frameworks/Sage.framework/Versions/9.7/local/var/lib/sage/venv-python3.10.5/share/texmf/tex/latex/sagetex for the default install of SageMath-9-7.app rather than the internal version in the .pkg ro update the one in the .pkg to 3.6.

I have no idea why everything worked fine with 9.6.

**Comment by culler** [comment]
Thank you Herb.  I am updating the .pkg installers in the two disk images now.  They will include version 3.6 of sagetex.sty.  And I will update my build script so it copies sagetex.sty from the sage repo instead of using a cached copy which can go out of date.

**Comment by culler** [comment]
I updated the two Sage 9.7 installer packages to include version 3.6 of sagetex.sty and signed and notarized the packages.  I built new disk images where the old installer packages were replaced by the new ones.  I signed and notarized those new disk images.  I uploaded the new disk images and new hash files to the release and bumped the version tag to 1.5.1.
