### ISSUE TITLE
9.8 pre-release doesn't have the sagetex.sty update to 3.6.1

### ISSUE THREAD

**Issue by herbs** [3-manifolds/Sage_macOS#52]
I believe there has been a small update to sagetex.sty to version 3.6.1 but the auxiliary package installs 3.6.

**Comment by culler** [comment]
Thanks.  I will update the package.

**Comment by culler** [comment]
It looks to me like the sagetex.sty file in Recommended_9_8.pkg is actually up to date.  It is true that the sagetex package now has version 3.6.1.  But the sagetex.sty file in that package is identical to the one which is included in Recommended_9_8.pkg.  Something else in the sagetex package must have changed.

**Comment by culler** [comment]
I think this can be closed since there has been no change to sagetex.sty.
