### ISSUE TITLE
Problem accessing the jupyter notebook under Ventura 13.2.1

### ISSUE THREAD

**Issue by castal** [3-manifolds/Sage_macOS#53]
I recently upgraded to macOS Ventura, and that seems to have broken the ability of Sage_macOS to access the Jupyter notebook. It was working just fine under macOS 12 (Monterey), but now the Chrome browser is telling me:

    "This site can’t be reached localhost refused to connect."

When I ask for more details, I get:

    "Allow Chrome to access the network in your firewall or antivirus settings.
    If it is already listed as a program allowed to access the network, try removing it from the list and adding it again."

But I am not using an antivirus application and my mac tells me that the macOS Firewall is inactive.

I am OK for now just using a little shell script, "sage -n jupyter --notebook-dir [my sage directory]", but I thought that if you haven't upgraded to Ventura, then maybe you won't have seen this hiccup.

**Comment by culler** [comment]
I think this is the same as issue #28.  Please try:
`rm -rf ~/Library/Application\ Support/SageMath/Jupyter`

**Comment by castal** [comment]
Bingo!!!  Thanks very much!

**Comment by culler** [comment]
Glad to hear it.
