### ISSUE TITLE
Problem with SageMath in Ubuntu(WSL)

### ISSUE THREAD

**Issue by DDLelouch** [3-manifolds/Sage_macOS#54]
galois@HL-BT1:~$ sage
/usr/bin/sage-env: line 122: cd: /path/to/sage: No such file or directory
Warning: overwriting SAGE_ROOT environment variable:
Old SAGE_ROOT=/path/to/sage
New SAGE_ROOT=
Traceback (most recent call last):
  File "/usr/bin/sage-ipython", line 9, in <module>
    from sage.misc.banner import banner
ModuleNotFoundError: No module named 'sage.misc'

How can I solve this?

**Comment by NathanDunfield** [comment]
This is the issue tracker for the macOS binary distribution of Sage, so you should direct your query [elsewhere](https://www.sagemath.org/help.html).

**Comment by DDLelouch** [comment]
> This is the issue tracker for the macOS binary distribution of Sage, so you should direct your query [elsewhere](https://www.sagemath.org/help.html).

Thks, my bad, i didnt tell that i  was using wsl ubuntu 22.04
