### ISSUE TITLE
Jupyterlab

### ISSUE THREAD

**Issue by mocenigo** [3-manifolds/Sage_macOS#56]
Hi, it seems that there is no way to run this with JupyterLab?

**Comment by culler** [comment]
I don't know why it "seems" that way to you.  It works for me.  Did you install the extra package in the disk image, so that the SageMath jupyter kernel would become visible to jupyter-lab?  What did you try?  Your report doesn't say.

**Comment by mocenigo** [comment]
Well, I have installed both sagemath and the extra package. When I start the sagemath application, it still starts with the old jupyterlab. I have tried quite a few suggestions found on the net, like installing (on top of this) jupyterlab from within sage, and restarting it. Nothing. Mind you, something like the ability to choose Jupyterlab should to be an optional and obscure function, but something that is obvious from the starter application, like a button to press, or it is a UX fail.

**Comment by culler** [comment]
The enhancement suggested here has been implemented in the new pre-release of SageMAth 10.1 for macOS.  Please give it a try and let us know how it goes.

**Comment by mocenigo** [comment]
It works nicely here, and it also remembers the previous choice! neat!

**Comment by culler** [comment]
Great!  Thanks for the suggestion.
