### ISSUE TITLE
2.01 x86-64 version starts up and quits; arm-64 version works fine.

### ISSUE THREAD

**Issue by herbs** [3-manifolds/Sage_macOS#57]
I think the title says it all

**Comment by culler** [comment]
Thanks @herbs for volunteering as a beta tester!

Can you please do two things:

1) Open a terminal and run /Applications/SageMath-10-1.app/Contents/MacOS/SageMath
    Please report what the traceback says.

2) Provide the contents of ~/Library/Application\ Support/SageMath/Settings.plist

Thanks!

**Comment by herbs** [comment]
> On Jun 15, 2023, at 7:48 AM, Marc Culler ***@***.***> wrote:
> 
> 
> Thanks @herbs for volunteering as a beta tester!
> Can you please do two things:
>     • Open a terminal and run /Applications/SageMath-10-1.app/Contents/MacOS/SageMath
> Please report what the traceback says.
>     • Provide the contents of ~/Library/Application\ Support/SageMath/Settings.plist
> Thanks!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Howdy,

Here are the files:


% /Applications/SageMath-10-1.app/Contents/MacOS/SageMath                Traceback (most recent call last):
  File "/Applications/SageMath-10-1.app/Contents/Resources/main.py", line 610, in <module>
    SageApp().run()
  File "/Applications/SageMath-10-1.app/Contents/Resources/main.py", line 599, in run
    self.launcher = LaunchWindow(root=self.root_window)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/SageMath-10-1.app/Contents/Resources/main.py", line 208, in __init__
    if self.settings['state']['notebook_type'] == 'Jupyter Lab':
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'notebook_type'




Good Luck,

Herb Schulz
***@***.***

**Comment by herbs** [comment]
Sigh... the plist file didn't transfer. Here's a copy:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>state</key>
	<dict>
		<key>interface_type</key>
		<string>cli</string>
		<key>notebook_dir</key>
		<string></string>
		<key>terminal_app</key>
		<string>Terminal.app</string>
	</dict>
</dict>
</plist>

**Comment by herbs** [comment]
Hmmm:
[SettingsPlist.txt](https://github.com/3-manifolds/Sage_macOS/files/11758078/SettingsPlist.txt)

**Comment by culler** [comment]
OK.  The new assets have been uploaded.  They work for me.  Please let me know if you have any further trouble.

**Comment by culler** [comment]
Yes, both versions have  changed.  You should download the arm version too. (The change was in the pure python part.) Whether it crashes depends on the data you have in your settings.
