### ISSUE TITLE
Can't start Sage notebook by double-clicking application icon (unable to connect to localhost:8888)

### ISSUE THREAD

**Issue by neldredge-unco** [3-manifolds/Sage_macOS#61]
Starting a few days ago, when I double-click the Sage application icon, selecting Notebook: Classic Jupyter, my browser redirects to a localhost URL (http://localhost:8888/tree?token=addf...) that doesn't work.  Firefox reports "Unable to connect. Firefox can’t establish a connection to the server at localhost:8888." Running `sage -n jupyter` from the command line does work.

Possibly relevant is that the localhost URL always has the same token in it, even when starting the application several times.  That seems like it might not be right.  On the other hand, `ps ax` doesn't seem to show any sage processes running at all.

This used to work.  I am not sure what changed, except that I upgraded from Ventura 13.6 to 13.6.2 around the same time.  I don't recall if this is exactly when it stopped working, though.

I tried reinstalling Sage both through homebrew and from copying directly from the dmg, with the same result.

For diagnosis, is there a simple way to see what the GUI launcher is running, and what output or errors it might be producing?

**Comment by culler** [comment]
I think this might be a duplicate 0f #28 -- it seems to still happen with system upgrades.  Please try the (updated) recommendation from that ticket:

Delete the folder: ~/Library/Application Support/SageMath/10.1/Jupyter

**Comment by neldredge-unco** [comment]
Yes, that fixed it.  Thanks!

Duplicate of #28
