### ISSUE TITLE
Something is broken in RC4 with OSX 14.4

### ISSUE THREAD

**Issue by brunoh2015** [3-manifolds/Sage_macOS#63]
After installing the new version v2.3-RC4 for amg64 on Mac OSX 14.4, it is impossible to launch the Notebook version of Sagemath (the command line version works fine) and susbsequently to quit the software.  I had to use force quit 

Everything worked fine with the v2.3-RC3 on Mac OSX 14.3.1

**Comment by brunoh2015** [comment]
Thank you for your quick & clear answer

Here is the traceback I obtained through terminal. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/SageMath-10-3.app/Contents/Frameworks/Sage.framework/Versions/Current/venv/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Applications/SageMath-10-3.app/Contents/Resources/main.py", line 338, in launch_sage
    launched = self.launch_notebook('jupyterlab')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/SageMath-10-3.app/Contents/Resources/main.py", line 150, in launch_notebook
    json_files = [f for f in os.listdir(jupyter_runtime_dir)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bh/Library/Application Support/SageMath-10-3/Jupyter/runtime’

**Comment by culler** [comment]
If you download the latest pre-release version it should automatically create that directory if it does not exist.  The disk image that had that bug was only up for a few hours, but you managed to get a copy.

**Comment by brunoh2015** [comment]
You were right all along ! Thank you so much.

Everything works perfectly fine now. Problem solved

**Comment by culler** [comment]
Thanks for letting us know!
