### ISSUE TITLE
Version updates and data issues

### ISSUE THREAD

**Issue by n-WN** [3-manifolds/Sage_macOS#64]
It is currently 10.1. Is there a way to upgrade to version 10.3 without losing data (modules installed in version 10.1)?

**Comment by culler** [comment]
When you install a PyPI package with the %pip command in SageMath it gets installed in
your home directory.  Specifically, these packages are installed in `~/.sage/local/lib/python3.XX`
where XX is the version of python3 included in the SageMath that installed the package.  Those packages are not removed by the installer.  But they are only useful if the new Sage uses the same version of Python3.  SageMath-10.1 used Python3.11, as will SageMath-10.3 when it gets released.  So the packages that you installed with 10.1 should still be available with 10.3.

I am expecting to release 10.3 in the next few days.

**Comment by culler** [comment]
I just noticed that if you use brew cask to install SageMath you should be careful about uninatalling the previous version.  It looks like the uninstall recipe might remove your .sage directory, which would remove the PyPI packages that you installed with %pip in the previous version of SageMath.

**Comment by n-WN** [comment]
> I just noticed that if you use brew cask to install SageMath you should be careful about uninatalling the previous version. It looks like the uninstall recipe might remove your .sage directory, which would remove the PyPI packages that you installed with %pip in the previous version of SageMath.

My sagemath was downloaded and installed from github without using brew, but thank you for reminding me.
