### ISSUE TITLE
Unable to start SageMath 10.3 on MacOS Ventura 13.6.3

### ISSUE THREAD

**Issue by CH4O7IC** [3-manifolds/Sage_macOS#68]
I installed SageMath today. Copied the .app to /Applications and ran the recommended package.
When I try to open a session via the app and spotlight, port 8888 is not responding.
When I try to start a session via the terminal I don't seem to have permission to do so without sudo privileges and doing it with sudo fails. I attached a screenshot displaying that.

<img width="1480" alt="Screenshot 2024-04-10 at 15 47 17" src="https://github.com/3-manifolds/Sage_macOS/assets/76394509/6269c61a-fe0a-4873-93c8-589f00ab2a90">

**Comment by CH4O7IC** [comment]
I didn't screenshot the sudo part. This is it:

<img width="1325" alt="Screenshot 2024-04-10 at 19 28 41" src="https://github.com/3-manifolds/Sage_macOS/assets/76394509/836a2cbc-1279-43bd-bbeb-6927128c663b">

**Comment by CH4O7IC** [comment]
I'm sorry if the spotlight part was unclear. I simply meant that I used the built-in App-Runner Spotlight (typically Command+Space) to run the SageMath*.app from the Applications.
I will try deleting the Jupyter directories later and come back to this if there's any more problems.
Thanks a lot. :D

**Comment by CH4O7IC** [comment]
Removing the ~/Library/Jupyter and ~/.sage directories did the job just fine. It works as intended now. Thanks

**Comment by culler** [comment]
Thank you.  I am glad to hear that.
