### ISSUE TITLE
Selecting algorithm for canonical_label()

### ISSUE THREAD

**Issue by gordonfroyle** [3-manifolds/Sage_macOS#73]
I have had some problems with this version - for example, I have to use Chrome rather than Safari to open a Jupyter notebook.

However what I am more concerned about is this short bit of code (running on M3 MacBook Pro with 14.6.1). 

p = graphs.PetersenGraph()
print(is_package_installed('bliss'))
p.canonical_label(algorithm='bliss')

True
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/tl/1hqgtqx95tn9ctv2wj6bxby5_c62xz/T/ipykernel_84047/166102069.py in ?()
      1 p = graphs.PetersenGraph()
      2 print(is_package_installed('bliss'))
----> 3 p.canonical_label(algorithm='bliss')

/private/var/tmp/sage-10.4-current/local/var/lib/sage/venv-python3.12.4/lib/python3.12/site-packages/sage/graphs/generic_graph.py in ?(self, partition, certificate, edge_labels, algorithm, return_graph)
  24689             raise NotImplementedError("algorithm 'bliss' cannot be used for graph with multiedges")
  24690 
  24691         # Check bliss if explicitly requested, raise if not found.
  24692         if algorithm == 'bliss':
> 24693             from sage.graphs.bliss import canonical_form
  24694 
  24695         # By default use bliss when possible
  24696         elif algorithm is None:

ModuleNotFoundError: No module named 'sage.graphs.bliss'

**Comment by culler** [comment]
Thank you for your report, and sorry I took so long to respond.

The reason that you need to use Chrome (or Firefox) instead of Safari is that your Safari has cached some out-of-date versions of Jupyter javascript files.  This is a common problem with Jupyter notebooks.  The fix is to clear your cache, for example by holding the shift key while clicking the reload button.  Jupyter notebook pages contain only javascript, and any javascript error, e.g. an undefined variable, causes a blank page.

The problem with sage.graphs.bliss seems to be a Sage build error.  The file bliss.pyx exists but is not being compiled with cython to produce the sage.graphs.bliss extension module.  I am looking into how to fix this.

**Comment by culler** [comment]
It seems that it is not a build error, but a configuration change.  The graphs.bliss module was reconfigured as an optional package which is not enabled by default.  I did not know that.  I will attempt to enable it in the forthcoming 10.5 release.

**Comment by gordonfroyle** [comment]
> It seems that it is not a build error, but a configuration change. The graphs.bliss module was reconfigured as an optional package which is not enabled by default. I did not know that. I will enable it in the forthcoming 10.5 release.

Thank you for working on this - I am just grateful to be able to install new versions of SageMath on Mac so easily.

**Comment by culler** [comment]
@gordonfroyle:  I have updated the pre-release versions of SageMath 10.5.  The new ones should include the graphs.bliss module.  Can you please test whether the behavior is now what you expect?

**Comment by gordonfroyle** [comment]
Yes, I can now ask

g.canonical_label(algorithm=’bliss’)

and it runs as expected.

Thanks

From: Marc Culler ***@***.***>
Date: Friday, 1 November 2024 at 5:18 am
To: 3-manifolds/Sage_macOS ***@***.***>
Cc: Gordon Royle ***@***.***>, Mention ***@***.***>
Subject: Re: [3-manifolds/Sage_macOS] Selecting algorithm for canonical_label() (Issue #73)

@gordonfroyle<https://github.com/gordonfroyle>: I have updated the pre-release versions of SageMath 10.5. The new ones should include the graphs.bliss module. Can you please test whether the behavior is now what you expect?

**Comment by culler** [comment]
Good news!  Thanks.  I will close this ticket.
