### ISSUE TITLE
2.5.0 beta crashes on startup

### ISSUE THREAD

**Issue by herbs** [3-manifolds/Sage_macOS#76]
On initial startup the 2.5.0 beta crashes. This is under Sequoia 15.0.1.
[crash report.txt](https://github.com/user-attachments/files/17461082/crash.report.txt)

**Comment by culler** [comment]
Thanks @herbs.  It didn't crash on my computer with Sequoia.  What hardware are you using?

**Comment by culler** [comment]
I can see the crash on Arm with Sequoia 15.1beta.  I will remove the Arm dmg and try again.  Thanks for the test!

**Comment by culler** [comment]
@herbs - I have now replaced the arm64 disk image.  The arm64 app runs on my M1 system with no crash.

The problem appears to have been an invalid signature.  You might expect that Apple's notarizer would not notarize an app with an invalid signature.  But, in fact, it will.  You might also expect that if an app is blocked for having an invalid signature then the crash report would say so.  But, in fact, it doesn't.  I reports an invalid instruction.

Anyway, please let me know if the new disk image works for you.

**Comment by herbs** [comment]
> On Oct 21, 2024, at 3:41 PM, Marc Culler ***@***.***> wrote:
> 
> 
> @herbs - I have now replaced the arm64 disk image. The arm64 app runs on my M1 system with no crash.
> The problem appears to have been an invalid signature. You might expect that Apple's notarizer would not notarize an app with an invalid signature. But, in fact, it will. You might also expect that if an app is blocked for having an invalid signature then the crash report would say so. But, in fact, it doesn't. I reports an invalid instruction.
> Anyway, please let me know if the new disk image works for you.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Howdy,

Loads fine now! Thanks for the work you put into creating this app.

Good Luck,

Herb Schulz
***@***.***

**Comment by culler** [comment]
Good news!  I will close this ticket now.

**Comment by culler** [comment]
Closing this ticket.
