### ISSUE TITLE
SageTex Not Installed?

### ISSUE THREAD

**Issue by enthor** [3-manifolds/Sage_macOS#9]
7.2. MakeSageTeXknowntoTeX references directories and files which I do not see. 

I did go ahead and install MacTex, which seemed correct. Now i am looking to finalize using method 3, "The third (and best) way to make TeX aware of sagetex.sty is to copy that file into a convenient place in your home directory".  Running 'kpsewhich -var-value=TEXMFHOME' yields

/Users/user6/Library/texmf

which does not exist???

And usr/local/share/texmf/tex does not exist either.

I also cannot find sagetext.sty because usr/local/share/texmf/tex/latex/sagetex/ does not exit.

I also do not see the referenced documentation, usr/local/share/doc/sagetex/sagetex.pdf

On my system, I believe SAGE_ROOT = usr and I have Finder set to show the invisible system
files, via shift+command+. so ... the stuff should be there. I just can't find SageTex at all.

/usr/local/share contains:

doc		ghostscript	jupyter		man

/usr/local/share/doc contains

ghostscript

* * *

Just as an aside, Tutorial 1.3 says, "Sage’s intended audience is mathematics students (from high school to graduate school), teachers, and research mathematicians." 

In my view, this SageTex -> LaTex install procedure is too hard. I can't imagine telling high school students to do this.

**Comment by NathanDunfield** [comment]
> Running 'kpsewhich -var-value=TEXMFHOME' yields
> 
> /Users/user6/Library/texmf
> 
> which does not exist???

You should create the above directory and put the `.sty` file there.  MacTeX does not create it during installation, but it is still the default location it looks for such files.

> On my system, I believe SAGE_ROOT = usr

It's not going to be `usr`.  You can figure out what is it like this:
```
sage: import os                                                                 
sage: os.environ['SAGE_ROOT']                                                   
'/Applications/SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3.rc4'
```

**Comment by enthor** [comment]
OK! I think I have performed this step correctly:

`# kpsewhich -var-value=TEXMFHOME
# cp -R SAGE_ROOT/local/share/texmf/tex TEXMFHOME
cp -R /Applications/SageMath-9-3.app/Contents/Frameworks/Sage.framework/Versions/9.3.rc4/local/share/texmf/tex /users/User6/Library/texmf`

The only problem was that the tex/ directory contained what appears to be a symbolic
reference to TEXMFHOME and the cp command looped with the cyclic reference 
("File name too long"). But it copied tex/ so, ok!

From what you said, and I originally thought I understood, I just needed the sagetext.sty
file, not the whole tex/ directory. BUT the SageTutorial in 7.2 gives a command:

`cp -R SAGE_ROOT/local/share/texmf/tex TEXMFHOME`

indicating that tex/ should be copied. 

Unfortunately, I don't yet have the skills to even test this configuration
since I don't yet know how to use Latex from command line. For now I am
going to just put this effort on hold. . I think it will all become clear to me 
after I invest the time in learning Latex.

Thank you for helping!
